"""Add break_minutes and note fields to attendance table

Revision ID: a1b2c3d4e5f6
Revises: 7adf24cc9b4a
Create Date: 2025-09-27 13:57:41.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = '7adf24cc9b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('break_minutes', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('attendance', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'note')
    op.drop_column('attendance', 'break_minutes')
    # ### end Alembic commands ###
