"""add_break_minutes_and_note_to_attendance"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_break_minutes_and_note'
down_revision = '7adf24cc9b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('break_minutes', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('note', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('note')
        batch_op.drop_column('break_minutes')

    # ### end Alembic commands ###
